### ISSUE TITLE
Cannot push to repository

### ISSUE THREAD

**Issue by bwhitchurch** [atla5e/atla5e.github.io#1]
Repro:
1. Create new branch using `git checkout -b bwhitchurch/test-branch`
2. Make a commit, I modified one of the _recipes files and commited to the branch
3. Try to push using `git push -u `bwhitchurch/test-branch`. Does not work.
4. Try again with `git push --set-upstream origin bwhitchurch/test-branch` also does not work `ERROR: Permission to atla5e/atla5e.github.io.git denied to bwhitchurch`

**Comment by mbenlioglu** [comment]
Granted permission
